// author polikuo 2018
// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef editor_h
#define editor_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Text_Editor.H>
#include <FL/Fl_Menu_Bar.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_File_Chooser.H>
#include <errno.h>
void buffer_init();
void shebang();
void new_cb();
void save_file(const char *newfile);
void saveas_cb();
void save_cb();
void open_cb();
void load_file(char *newfile);
void style_unfinished_cb(int, void*);
void busybox();
int is_special(char ascii);
void stylebuf_init();
void use_coloring();
void disable_color();
void color_cb();
int auto_indent_cb(int lsp, int pos, char *line);
void modification_cb(int pos, int nInserted, int nDeleted, int nRestyled, const char *deletedText, void *cbArg);
void ts_cb();
void ss_cb();
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *win;
#include <FL/Fl_Text_Editor.H>
extern Fl_Text_Editor *edit;
#include <FL/Fl_Menu_Bar.H>
extern Fl_Menu_Bar *menu_bar;
extern Fl_Menu_Item menu_menu_bar[];
#define file_menu (menu_menu_bar+0)
#define new_bt (menu_menu_bar+1)
#define open (menu_menu_bar+2)
#define save (menu_menu_bar+3)
#define saveas (menu_menu_bar+4)
#define shell_menu (menu_menu_bar+6)
#define sh (menu_menu_bar+7)
#define bash (menu_menu_bar+8)
#define color_switch (menu_menu_bar+10)
#define ts_btn (menu_menu_bar+11)
#define ss_btn (menu_menu_bar+12)
void scan_forward(int pos);
#endif
